SELECT 
    CITY,
    LENGTH(CITY)
FROM
    STATION
WHERE 
    (LAT_N IS NOT NULL) AND
    (LONG_W IS NOT NULL) 
ORDER BY LENGTH(CITY), CITY ASC
LIMIT 1
;

SELECT 
    CITY, LENGTH(CITY)
FROM
    STATION
WHERE
    (LAT_N IS NOT NULL)
        AND (LONG_W IS NOT NULL)
ORDER BY LENGTH(CITY) DESC , CITY DESC
LIMIT 1
;